CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
    LOCATION_X FLOAT8 NOT NULL,
    LOCATION_Y FLOAT8 NOT NULL,
    DISTANCE FLOAT8 NOT NULL
);