version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: r2dbc
      POSTGRES_DB: promocervausers

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080